/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface BaseUltraVerifierInterface extends utils.Interface {
  contractName: "BaseUltraVerifier";
  functions: {
    "getVerificationKeyHash()": FunctionFragment;
    "verify(bytes,bytes32[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getVerificationKeyHash",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verify",
    values: [BytesLike, BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "getVerificationKeyHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verify", data: BytesLike): Result;

  events: {};
}

export interface BaseUltraVerifier extends BaseContract {
  contractName: "BaseUltraVerifier";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BaseUltraVerifierInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getVerificationKeyHash(overrides?: CallOverrides): Promise<[string]>;

    verify(
      _proof: BytesLike,
      _publicInputs: BytesLike[],
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  getVerificationKeyHash(overrides?: CallOverrides): Promise<string>;

  verify(
    _proof: BytesLike,
    _publicInputs: BytesLike[],
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    getVerificationKeyHash(overrides?: CallOverrides): Promise<string>;

    verify(
      _proof: BytesLike,
      _publicInputs: BytesLike[],
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    getVerificationKeyHash(overrides?: CallOverrides): Promise<BigNumber>;

    verify(
      _proof: BytesLike,
      _publicInputs: BytesLike[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getVerificationKeyHash(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verify(
      _proof: BytesLike,
      _publicInputs: BytesLike[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
